### 1. Importa el paquete NUMPY bajo el nombre np.

In [1]:
#[tu código aquí]
import numpy as np

### 2. Imprime la versión de NUMPY y la configuración.

In [12]:
#[tu código aquí]
version = np.version.full_version
version

'1.26.4'

### 3. Genera un array tridimensional de 2x3x5 con valores aleatorios. Asigna el array a la variable "a"
 Desafío: hay al menos tres maneras fáciles que usan numpy para generar arrays aleatorios. ¿Cuántas formas puedes encontrar?

In [19]:
#[tu código aquí]
a = np.random.randint(0, 10, size=(2, 3, 5))
a = np.array(a)


### 4. Imprime a.

In [20]:
#[tu código aquí]
a

array([[[1, 8, 4, 0, 6],
        [2, 0, 3, 7, 2],
        [1, 7, 8, 5, 0]],

       [[5, 4, 6, 3, 8],
        [7, 9, 8, 4, 8],
        [5, 8, 2, 4, 7]]])

### 5. Crea un array tridimensional de 5x2x3 con todos los valores igual a 1.
Asigna el array a la variable "b"

In [25]:
#[tu código aquí]
b = np.ones((5, 2, 3))
b = np.array(b)

### 6. Imprime b.

In [26]:
#[tu código aquí]
b

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

### 7. ¿Tienen a y b el mismo tamaño? ¿Cómo lo demuestras en código Python?

In [27]:
#[tu código aquí]
len(a) == len(b)


False

### 8. ¿Es posible sumar a y b? ¿Por qué sí o por qué no?

In [31]:
#[tu código aquí]
suma = a + b
suma
'''
porque no te lo permite el broadcasting

'''


ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

### 9. Transpone b para que tenga la misma estructura que a (es decir, se convierta en un array de 2x3x5). Asigna el array transpuesto a la variable "c".


In [33]:
#[tu código aquí]
c = b.transpose(1,2,0)
c

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

### 10. Intenta sumar a y c. Ahora debería funcionar. Asigna la suma a la variable "d". Pero, ¿por qué funciona ahora?

In [35]:
#[tu código aquí]
d = a + c
d

array([[[ 2.,  9.,  5.,  1.,  7.],
        [ 3.,  1.,  4.,  8.,  3.],
        [ 2.,  8.,  9.,  6.,  1.]],

       [[ 6.,  5.,  7.,  4.,  9.],
        [ 8., 10.,  9.,  5.,  9.],
        [ 6.,  9.,  3.,  5.,  8.]]])

### 11. Imprime a y d. ¿Notas la diferencia y la relación entre los dos arrays en términos de los valores? Explica.

In [36]:
#[tu código aquí]
print('A',a)
print('D',d)

A [[[1 8 4 0 6]
  [2 0 3 7 2]
  [1 7 8 5 0]]

 [[5 4 6 3 8]
  [7 9 8 4 8]
  [5 8 2 4 7]]]
D [[[ 2.  9.  5.  1.  7.]
  [ 3.  1.  4.  8.  3.]
  [ 2.  8.  9.  6.  1.]]

 [[ 6.  5.  7.  4.  9.]
  [ 8. 10.  9.  5.  9.]
  [ 6.  9.  3.  5.  8.]]]


### 12. Multiplica a y c. Asigna el resultado a e.

In [37]:
#[tu código aquí]
e = a * c
e

array([[[1., 8., 4., 0., 6.],
        [2., 0., 3., 7., 2.],
        [1., 7., 8., 5., 0.]],

       [[5., 4., 6., 3., 8.],
        [7., 9., 8., 4., 8.],
        [5., 8., 2., 4., 7.]]])

### 13. ¿Es e igual a a? ¿Por qué sí o por qué no?

In [38]:
#[tu código aquí]
is_igual = a == e
is_igual

array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])

### 14. Identifica los valores máximos, mínimos y medios en d. Asigna esos valores a las variables "d_max", "d_min" y "d_mean"


In [40]:
#[tu código aquí]
d_min = np.min(d)
print("min",d_min)
d_max = np.max(d)
print("max",d_max)
d_mean = np.mean(d)
print("mean",d_mean)

min 1.0
max 10.0
mean 5.733333333333333


### 15. Ahora queremos etiquetar los valores en d. Primero crea un array vacío "f" con la misma forma (es decir, 2x3x5) que d usando `np.empty`.


In [44]:
#[tu código aquí]
f = np.empty((2,3,5))
f

array([[[4.79416779e-310, 0.00000000e+000, 5.51998348e+228,
         1.81270497e-152, 3.03061213e-152],
        [1.07332141e+200, 4.03235559e+175, 1.69337696e-152,
         4.76660077e+180, 5.98736697e+247],
        [6.01347002e-154, 9.07682851e+223, 8.79656417e+199,
         1.68821153e+195, 2.34783525e+251]],

       [[2.31633993e-152, 1.13072643e+277, 1.69592865e-152,
         1.44420365e+214, 5.98181094e-154],
        [6.01347002e-154, 2.34785706e+251, 5.45391402e-311,
         3.21142670e-322, 4.79512574e-310],
        [2.42092166e-322, 6.51961367e-310, 6.51961367e-310,
         4.79512558e-310, 6.51961367e-310]]])

### 16. Rellena los valores en f. Para cada valor en d, si es mayor que d_min pero menor que d_mean, asigna 25 al valor correspondiente en f.
- Si un valor en d es mayor que d_mean pero menor que d_max, asigna 75 al valor correspondiente en f.
- Si un valor es igual a d_mean, asigna 50 al valor correspondiente en f.
- Asigna 0 al valor correspondiente(s) en f para d_min en d.
- Asigna 100 al valor correspondiente(s) en f para d_max en d.
- Al final, f debería tener solo los siguientes valores: 0, 25, 50, 75 y 100.


In [45]:
#[tu código aquí]
f[(d > d_min) & (d < d_mean)] = 25
f[d == d_mean] = 50
f[(d > d_mean) & (d < d_max)] = 75
f[d == d_min] = 0
f[d == d_max] = 100
f

array([[[ 25.,  75.,  25.,   0.,  75.],
        [ 25.,   0.,  25.,  75.,  25.],
        [ 25.,  75.,  75.,  75.,   0.]],

       [[ 75.,  25.,  75.,  25.,  75.],
        [ 75., 100.,  75.,  25.,  75.],
        [ 75.,  75.,  25.,  25.,  75.]]])

### 17. Imprime d y f. ¿Tienes el f esperado?
Por ejemplo, si tu d es:
```python
array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])
```

Tu f debería ser:
```python
array([[[ 75.,  75.,  75.,  25.,  75.],
        [ 75.,  75.,  25.,  25.,  25.],
        [ 75.,  25.,  75.,  75.,  75.]],
       [[ 25.,  25.,  25.,  25., 100.],
        [ 75.,  75.,  75.,  75.,  75.],
        [ 25.,  75.,   0.,  75.,  75.]]])
```

In [48]:
#[tu código aquí]
print("d",d)
print("f",f)


d [[[ 2.  9.  5.  1.  7.]
  [ 3.  1.  4.  8.  3.]
  [ 2.  8.  9.  6.  1.]]

 [[ 6.  5.  7.  4.  9.]
  [ 8. 10.  9.  5.  9.]
  [ 6.  9.  3.  5.  8.]]]
f [[[ 25.  75.  25.   0.  75.]
  [ 25.   0.  25.  75.  25.]
  [ 25.  75.  75.  75.   0.]]

 [[ 75.  25.  75.  25.  75.]
  [ 75. 100.  75.  25.  75.]
  [ 75.  75.  25.  25.  75.]]]


### 18. Pregunta de bonificación: en lugar de usar números (es decir, 0, 25, 50, 75 y 100), ¿cómo usar valores de cadena  ("A", "B", "C", "D" y "E") para etiquetar los elementos del array? Esperas el resultado sea:

```python
array([[[ 'D',  'D',  'D',  'B',  'D'],
        [ 'D',  'D',  'B',  'B',  'B'],
        [ 'D',  'B',  'D',  'D',  'D']],
       [[ 'B',  'B',  'B',  'B',  'E'],
        [ 'D',  'D',  'D',  'D',  'D'],
        [ 'B',  'D',   'A',  'D', 'D']]])
```


In [ ]:
#[tu código aquí]
f[(d > d_min) & (d < d_mean)] = 25
f[d == d_mean] = 50
f[(d > d_mean) & (d < d_max)] = 75
f[d == d_min] = 0
f[d == d_max] = 100